// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/logging/v2/log_entry.proto

#include "google/logging/v2/log_entry.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_google_2fapi_2fmonitored_5fresource_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fapi_2fmonitored_5fresource_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_MonitoredResource;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fapi_2fmonitored_5fresource_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_MonitoredResourceMetadata;
}  // namespace protobuf_google_2fapi_2fmonitored_5fresource_2eproto
namespace protobuf_google_2flogging_2ftype_2fhttp_5frequest_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2flogging_2ftype_2fhttp_5frequest_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_HttpRequest;
}  // namespace protobuf_google_2flogging_2ftype_2fhttp_5frequest_2eproto
namespace protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_LogEntryOperation;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_LogEntrySourceLocation;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_LogEntry_LabelsEntry_DoNotUse;
}  // namespace protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto
namespace protobuf_google_2fprotobuf_2fany_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobuf_2fany_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Any;
}  // namespace protobuf_google_2fprotobuf_2fany_2eproto
namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobuf_2ftimestamp_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Timestamp;
}  // namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto
namespace protobuf_struct_5flite_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_struct_5flite_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ListValue;
}  // namespace protobuf_struct_5flite_2eproto
namespace google {
namespace logging {
namespace v2 {
class LogEntry_LabelsEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LogEntry_LabelsEntry_DoNotUse>
      _instance;
} _LogEntry_LabelsEntry_DoNotUse_default_instance_;
class LogEntryDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LogEntry>
      _instance;
  const ::google::protobuf::Any* proto_payload_;
  ::google::protobuf::internal::ArenaStringPtr text_payload_;
  const ::google::protobuf::Struct* json_payload_;
} _LogEntry_default_instance_;
class LogEntryOperationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LogEntryOperation>
      _instance;
} _LogEntryOperation_default_instance_;
class LogEntrySourceLocationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LogEntrySourceLocation>
      _instance;
} _LogEntrySourceLocation_default_instance_;
}  // namespace v2
}  // namespace logging
}  // namespace google
namespace protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto {
static void InitDefaultsLogEntry_LabelsEntry_DoNotUse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::logging::v2::_LogEntry_LabelsEntry_DoNotUse_default_instance_;
    new (ptr) ::google::logging::v2::LogEntry_LabelsEntry_DoNotUse();
  }
  ::google::logging::v2::LogEntry_LabelsEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LogEntry_LabelsEntry_DoNotUse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLogEntry_LabelsEntry_DoNotUse}, {}};

static void InitDefaultsLogEntry() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::logging::v2::_LogEntry_default_instance_;
    new (ptr) ::google::logging::v2::LogEntry();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::logging::v2::LogEntry::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<9> scc_info_LogEntry =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 9, InitDefaultsLogEntry}, {
      &protobuf_google_2fapi_2fmonitored_5fresource_2eproto::scc_info_MonitoredResource.base,
      &protobuf_google_2fprotobuf_2fany_2eproto::scc_info_Any.base,
      &protobuf_struct_5flite_2eproto::scc_info_ListValue.base,
      &protobuf_google_2fprotobuf_2ftimestamp_2eproto::scc_info_Timestamp.base,
      &protobuf_google_2flogging_2ftype_2fhttp_5frequest_2eproto::scc_info_HttpRequest.base,
      &protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntry_LabelsEntry_DoNotUse.base,
      &protobuf_google_2fapi_2fmonitored_5fresource_2eproto::scc_info_MonitoredResourceMetadata.base,
      &protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntryOperation.base,
      &protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntrySourceLocation.base,}};

static void InitDefaultsLogEntryOperation() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::logging::v2::_LogEntryOperation_default_instance_;
    new (ptr) ::google::logging::v2::LogEntryOperation();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::logging::v2::LogEntryOperation::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LogEntryOperation =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLogEntryOperation}, {}};

static void InitDefaultsLogEntrySourceLocation() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::logging::v2::_LogEntrySourceLocation_default_instance_;
    new (ptr) ::google::logging::v2::LogEntrySourceLocation();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::logging::v2::LogEntrySourceLocation::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LogEntrySourceLocation =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLogEntrySourceLocation}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_LogEntry_LabelsEntry_DoNotUse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LogEntry.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LogEntryOperation.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LogEntrySourceLocation.base);
}

}  // namespace protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto
namespace google {
namespace logging {
namespace v2 {

// ===================================================================

LogEntry_LabelsEntry_DoNotUse::LogEntry_LabelsEntry_DoNotUse() {}
LogEntry_LabelsEntry_DoNotUse::LogEntry_LabelsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void LogEntry_LabelsEntry_DoNotUse::MergeFrom(const LogEntry_LabelsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}

// ===================================================================

void LogEntry::InitAsDefaultInstance() {
  ::google::logging::v2::_LogEntry_default_instance_._instance.get_mutable()->resource_ = const_cast< ::google::api::MonitoredResource*>(
      ::google::api::MonitoredResource::internal_default_instance());
  ::google::logging::v2::_LogEntry_default_instance_._instance.get_mutable()->timestamp_ = const_cast< ::google::protobuf::Timestamp*>(
      ::google::protobuf::Timestamp::internal_default_instance());
  ::google::logging::v2::_LogEntry_default_instance_._instance.get_mutable()->receive_timestamp_ = const_cast< ::google::protobuf::Timestamp*>(
      ::google::protobuf::Timestamp::internal_default_instance());
  ::google::logging::v2::_LogEntry_default_instance_._instance.get_mutable()->http_request_ = const_cast< ::google::logging::type::HttpRequest*>(
      ::google::logging::type::HttpRequest::internal_default_instance());
  ::google::logging::v2::_LogEntry_default_instance_._instance.get_mutable()->metadata_ = const_cast< ::google::api::MonitoredResourceMetadata*>(
      ::google::api::MonitoredResourceMetadata::internal_default_instance());
  ::google::logging::v2::_LogEntry_default_instance_._instance.get_mutable()->operation_ = const_cast< ::google::logging::v2::LogEntryOperation*>(
      ::google::logging::v2::LogEntryOperation::internal_default_instance());
  ::google::logging::v2::_LogEntry_default_instance_._instance.get_mutable()->source_location_ = const_cast< ::google::logging::v2::LogEntrySourceLocation*>(
      ::google::logging::v2::LogEntrySourceLocation::internal_default_instance());
}
void LogEntry::unsafe_arena_set_allocated_resource(
    ::google::api::MonitoredResource* resource) {
  if (GetArenaNoVirtual() == NULL) {
    delete resource_;
  }
  resource_ = resource;
  if (resource) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.logging.v2.LogEntry.resource)
}
void LogEntry::clear_resource() {
  if (GetArenaNoVirtual() == NULL && resource_ != NULL) {
    delete resource_;
  }
  resource_ = NULL;
}
void LogEntry::set_allocated_proto_payload(::google::protobuf::Any* proto_payload) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_payload();
  if (proto_payload) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      proto_payload = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, proto_payload, submessage_arena);
    }
    set_has_proto_payload();
    payload_.proto_payload_ = proto_payload;
  }
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.LogEntry.proto_payload)
}
void LogEntry::clear_proto_payload() {
  if (has_proto_payload()) {
    if (GetArenaNoVirtual() == NULL) {
      delete payload_.proto_payload_;
    }
    clear_has_payload();
  }
}
void LogEntry::set_allocated_json_payload(::google::protobuf::Struct* json_payload) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_payload();
  if (json_payload) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(json_payload)->GetArena();
    if (message_arena != submessage_arena) {
      json_payload = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, json_payload, submessage_arena);
    }
    set_has_json_payload();
    payload_.json_payload_ = json_payload;
  }
  // @@protoc_insertion_point(field_set_allocated:google.logging.v2.LogEntry.json_payload)
}
void LogEntry::clear_json_payload() {
  if (has_json_payload()) {
    if (GetArenaNoVirtual() == NULL) {
      delete payload_.json_payload_;
    }
    clear_has_payload();
  }
}
void LogEntry::unsafe_arena_set_allocated_timestamp(
    ::google::protobuf::Timestamp* timestamp) {
  if (GetArenaNoVirtual() == NULL) {
    delete timestamp_;
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.logging.v2.LogEntry.timestamp)
}
void LogEntry::clear_timestamp() {
  if (GetArenaNoVirtual() == NULL && timestamp_ != NULL) {
    delete timestamp_;
  }
  timestamp_ = NULL;
}
void LogEntry::unsafe_arena_set_allocated_receive_timestamp(
    ::google::protobuf::Timestamp* receive_timestamp) {
  if (GetArenaNoVirtual() == NULL) {
    delete receive_timestamp_;
  }
  receive_timestamp_ = receive_timestamp;
  if (receive_timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.logging.v2.LogEntry.receive_timestamp)
}
void LogEntry::clear_receive_timestamp() {
  if (GetArenaNoVirtual() == NULL && receive_timestamp_ != NULL) {
    delete receive_timestamp_;
  }
  receive_timestamp_ = NULL;
}
void LogEntry::unsafe_arena_set_allocated_http_request(
    ::google::logging::type::HttpRequest* http_request) {
  if (GetArenaNoVirtual() == NULL) {
    delete http_request_;
  }
  http_request_ = http_request;
  if (http_request) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.logging.v2.LogEntry.http_request)
}
void LogEntry::clear_http_request() {
  if (GetArenaNoVirtual() == NULL && http_request_ != NULL) {
    delete http_request_;
  }
  http_request_ = NULL;
}
void LogEntry::unsafe_arena_set_allocated_metadata(
    ::google::api::MonitoredResourceMetadata* metadata) {
  if (GetArenaNoVirtual() == NULL) {
    delete metadata_;
  }
  metadata_ = metadata;
  if (metadata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.logging.v2.LogEntry.metadata)
}
void LogEntry::clear_metadata() {
  if (GetArenaNoVirtual() == NULL && metadata_ != NULL) {
    delete metadata_;
  }
  metadata_ = NULL;
}
void LogEntry::unsafe_arena_set_allocated_operation(
    ::google::logging::v2::LogEntryOperation* operation) {
  if (GetArenaNoVirtual() == NULL) {
    delete operation_;
  }
  operation_ = operation;
  if (operation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.logging.v2.LogEntry.operation)
}
void LogEntry::unsafe_arena_set_allocated_source_location(
    ::google::logging::v2::LogEntrySourceLocation* source_location) {
  if (GetArenaNoVirtual() == NULL) {
    delete source_location_;
  }
  source_location_ = source_location;
  if (source_location) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.logging.v2.LogEntry.source_location)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LogEntry::kLogNameFieldNumber;
const int LogEntry::kResourceFieldNumber;
const int LogEntry::kProtoPayloadFieldNumber;
const int LogEntry::kTextPayloadFieldNumber;
const int LogEntry::kJsonPayloadFieldNumber;
const int LogEntry::kTimestampFieldNumber;
const int LogEntry::kReceiveTimestampFieldNumber;
const int LogEntry::kSeverityFieldNumber;
const int LogEntry::kInsertIdFieldNumber;
const int LogEntry::kHttpRequestFieldNumber;
const int LogEntry::kLabelsFieldNumber;
const int LogEntry::kMetadataFieldNumber;
const int LogEntry::kOperationFieldNumber;
const int LogEntry::kTraceFieldNumber;
const int LogEntry::kSpanIdFieldNumber;
const int LogEntry::kTraceSampledFieldNumber;
const int LogEntry::kSourceLocationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LogEntry::LogEntry()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntry.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.logging.v2.LogEntry)
}
LogEntry::LogEntry(::google::protobuf::Arena* arena)
  : ::google::protobuf::MessageLite(),
  _internal_metadata_(arena),
  labels_(arena) {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntry.base);
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.logging.v2.LogEntry)
}
LogEntry::LogEntry(const LogEntry& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  labels_.MergeFrom(from.labels_);
  insert_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.insert_id().size() > 0) {
    insert_id_.SetLite(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.insert_id(),
      GetArenaNoVirtual());
  }
  log_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.log_name().size() > 0) {
    log_name_.SetLite(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.log_name(),
      GetArenaNoVirtual());
  }
  trace_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.trace().size() > 0) {
    trace_.SetLite(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.trace(),
      GetArenaNoVirtual());
  }
  span_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.span_id().size() > 0) {
    span_id_.SetLite(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.span_id(),
      GetArenaNoVirtual());
  }
  if (from.has_http_request()) {
    http_request_ = new ::google::logging::type::HttpRequest(*from.http_request_);
  } else {
    http_request_ = NULL;
  }
  if (from.has_resource()) {
    resource_ = new ::google::api::MonitoredResource(*from.resource_);
  } else {
    resource_ = NULL;
  }
  if (from.has_timestamp()) {
    timestamp_ = new ::google::protobuf::Timestamp(*from.timestamp_);
  } else {
    timestamp_ = NULL;
  }
  if (from.has_operation()) {
    operation_ = new ::google::logging::v2::LogEntryOperation(*from.operation_);
  } else {
    operation_ = NULL;
  }
  if (from.has_source_location()) {
    source_location_ = new ::google::logging::v2::LogEntrySourceLocation(*from.source_location_);
  } else {
    source_location_ = NULL;
  }
  if (from.has_receive_timestamp()) {
    receive_timestamp_ = new ::google::protobuf::Timestamp(*from.receive_timestamp_);
  } else {
    receive_timestamp_ = NULL;
  }
  if (from.has_metadata()) {
    metadata_ = new ::google::api::MonitoredResourceMetadata(*from.metadata_);
  } else {
    metadata_ = NULL;
  }
  ::memcpy(&severity_, &from.severity_,
    static_cast<size_t>(reinterpret_cast<char*>(&trace_sampled_) -
    reinterpret_cast<char*>(&severity_)) + sizeof(trace_sampled_));
  clear_has_payload();
  switch (from.payload_case()) {
    case kProtoPayload: {
      mutable_proto_payload()->::google::protobuf::Any::MergeFrom(from.proto_payload());
      break;
    }
    case kTextPayload: {
      set_text_payload(from.text_payload());
      break;
    }
    case kJsonPayload: {
      mutable_json_payload()->::google::protobuf::Struct::MergeFrom(from.json_payload());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:google.logging.v2.LogEntry)
}

void LogEntry::SharedCtor() {
  insert_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  log_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  trace_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  span_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&http_request_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&trace_sampled_) -
      reinterpret_cast<char*>(&http_request_)) + sizeof(trace_sampled_));
  clear_has_payload();
}

LogEntry::~LogEntry() {
  // @@protoc_insertion_point(destructor:google.logging.v2.LogEntry)
  SharedDtor();
}

void LogEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
  insert_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  log_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  trace_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  span_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete http_request_;
  if (this != internal_default_instance()) delete resource_;
  if (this != internal_default_instance()) delete timestamp_;
  if (this != internal_default_instance()) delete operation_;
  if (this != internal_default_instance()) delete source_location_;
  if (this != internal_default_instance()) delete receive_timestamp_;
  if (this != internal_default_instance()) delete metadata_;
  if (has_payload()) {
    clear_payload();
  }
}

void LogEntry::ArenaDtor(void* object) {
  LogEntry* _this = reinterpret_cast< LogEntry* >(object);
  (void)_this;
}
void LogEntry::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void LogEntry::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LogEntry& LogEntry::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntry.base);
  return *internal_default_instance();
}


void LogEntry::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:google.logging.v2.LogEntry)
  switch (payload_case()) {
    case kProtoPayload: {
      if (GetArenaNoVirtual() == NULL) {
        delete payload_.proto_payload_;
      }
      break;
    }
    case kTextPayload: {
      payload_.text_payload_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
          GetArenaNoVirtual());
      break;
    }
    case kJsonPayload: {
      if (GetArenaNoVirtual() == NULL) {
        delete payload_.json_payload_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = PAYLOAD_NOT_SET;
}


void LogEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:google.logging.v2.LogEntry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  labels_.Clear();
  insert_id_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  log_name_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  trace_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  span_id_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  if (GetArenaNoVirtual() == NULL && http_request_ != NULL) {
    delete http_request_;
  }
  http_request_ = NULL;
  if (GetArenaNoVirtual() == NULL && resource_ != NULL) {
    delete resource_;
  }
  resource_ = NULL;
  if (GetArenaNoVirtual() == NULL && timestamp_ != NULL) {
    delete timestamp_;
  }
  timestamp_ = NULL;
  if (GetArenaNoVirtual() == NULL && operation_ != NULL) {
    delete operation_;
  }
  operation_ = NULL;
  if (GetArenaNoVirtual() == NULL && source_location_ != NULL) {
    delete source_location_;
  }
  source_location_ = NULL;
  if (GetArenaNoVirtual() == NULL && receive_timestamp_ != NULL) {
    delete receive_timestamp_;
  }
  receive_timestamp_ = NULL;
  if (GetArenaNoVirtual() == NULL && metadata_ != NULL) {
    delete metadata_;
  }
  metadata_ = NULL;
  ::memset(&severity_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&trace_sampled_) -
      reinterpret_cast<char*>(&severity_)) + sizeof(trace_sampled_));
  clear_payload();
  _internal_metadata_.Clear();
}

bool LogEntry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:google.logging.v2.LogEntry)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .google.protobuf.Any proto_payload = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_proto_payload()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string text_payload = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_text_payload()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->text_payload().data(), static_cast<int>(this->text_payload().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.logging.v2.LogEntry.text_payload"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string insert_id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_insert_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->insert_id().data(), static_cast<int>(this->insert_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.logging.v2.LogEntry.insert_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Struct json_payload = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_json_payload()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.logging.type.HttpRequest http_request = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_http_request()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.api.MonitoredResource resource = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_resource()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Timestamp timestamp = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_timestamp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.logging.type.LogSeverity severity = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_severity(static_cast< ::google::logging::type::LogSeverity >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, string> labels = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          LogEntry_LabelsEntry_DoNotUse::Parser< ::google::protobuf::internal::MapFieldLite<
              LogEntry_LabelsEntry_DoNotUse,
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&labels_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.logging.v2.LogEntry.LabelsEntry.key"));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.logging.v2.LogEntry.LabelsEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string log_name = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u /* 98 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_log_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->log_name().data(), static_cast<int>(this->log_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.logging.v2.LogEntry.log_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.logging.v2.LogEntryOperation operation = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(122u /* 122 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_operation()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string trace = 22;
      case 22: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(178u /* 178 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_trace()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->trace().data(), static_cast<int>(this->trace().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.logging.v2.LogEntry.trace"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.logging.v2.LogEntrySourceLocation source_location = 23;
      case 23: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(186u /* 186 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_source_location()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Timestamp receive_timestamp = 24;
      case 24: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(194u /* 194 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_receive_timestamp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.api.MonitoredResourceMetadata metadata = 25;
      case 25: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(202u /* 202 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_metadata()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string span_id = 27;
      case 27: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(218u /* 218 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_span_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->span_id().data(), static_cast<int>(this->span_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.logging.v2.LogEntry.span_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool trace_sampled = 30;
      case 30: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(240u /* 240 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &trace_sampled_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.logging.v2.LogEntry)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.logging.v2.LogEntry)
  return false;
#undef DO_
}

void LogEntry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.logging.v2.LogEntry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Any proto_payload = 2;
  if (has_proto_payload()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_proto_payload(), output);
  }

  // string text_payload = 3;
  if (has_text_payload()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->text_payload().data(), static_cast<int>(this->text_payload().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.logging.v2.LogEntry.text_payload");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->text_payload(), output);
  }

  // string insert_id = 4;
  if (this->insert_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->insert_id().data(), static_cast<int>(this->insert_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.logging.v2.LogEntry.insert_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->insert_id(), output);
  }

  // .google.protobuf.Struct json_payload = 6;
  if (has_json_payload()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      6, this->_internal_json_payload(), output);
  }

  // .google.logging.type.HttpRequest http_request = 7;
  if (this->has_http_request()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->_internal_http_request(), output);
  }

  // .google.api.MonitoredResource resource = 8;
  if (this->has_resource()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      8, this->_internal_resource(), output);
  }

  // .google.protobuf.Timestamp timestamp = 9;
  if (this->has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, this->_internal_timestamp(), output);
  }

  // .google.logging.type.LogSeverity severity = 10;
  if (this->severity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      10, this->severity(), output);
  }

  // map<string, string> labels = 11;
  if (!this->labels().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.logging.v2.LogEntry.LabelsEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.logging.v2.LogEntry.LabelsEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->labels().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->labels().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->labels().begin();
          it != this->labels().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<LogEntry_LabelsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(labels_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessage(
            11, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<LogEntry_LabelsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->labels().begin();
          it != this->labels().end(); ++it) {
        entry.reset(labels_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessage(
            11, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(&*it);
      }
    }
  }

  // string log_name = 12;
  if (this->log_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->log_name().data(), static_cast<int>(this->log_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.logging.v2.LogEntry.log_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->log_name(), output);
  }

  // .google.logging.v2.LogEntryOperation operation = 15;
  if (this->has_operation()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      15, this->_internal_operation(), output);
  }

  // string trace = 22;
  if (this->trace().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->trace().data(), static_cast<int>(this->trace().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.logging.v2.LogEntry.trace");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      22, this->trace(), output);
  }

  // .google.logging.v2.LogEntrySourceLocation source_location = 23;
  if (this->has_source_location()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      23, this->_internal_source_location(), output);
  }

  // .google.protobuf.Timestamp receive_timestamp = 24;
  if (this->has_receive_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      24, this->_internal_receive_timestamp(), output);
  }

  // .google.api.MonitoredResourceMetadata metadata = 25;
  if (this->has_metadata()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      25, this->_internal_metadata(), output);
  }

  // string span_id = 27;
  if (this->span_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->span_id().data(), static_cast<int>(this->span_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.logging.v2.LogEntry.span_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      27, this->span_id(), output);
  }

  // bool trace_sampled = 30;
  if (this->trace_sampled() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(30, this->trace_sampled(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:google.logging.v2.LogEntry)
}

size_t LogEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.logging.v2.LogEntry)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // map<string, string> labels = 11;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->labels_size());
  {
    ::std::unique_ptr<LogEntry_LabelsEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->labels().begin();
        it != this->labels().end(); ++it) {
      if (entry.get() != NULL && entry->GetArena() != NULL) {
        entry.release();
      }
      entry.reset(labels_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
    if (entry.get() != NULL && entry->GetArena() != NULL) {
      entry.release();
    }
  }

  // string insert_id = 4;
  if (this->insert_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->insert_id());
  }

  // string log_name = 12;
  if (this->log_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->log_name());
  }

  // string trace = 22;
  if (this->trace().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->trace());
  }

  // string span_id = 27;
  if (this->span_id().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->span_id());
  }

  // .google.logging.type.HttpRequest http_request = 7;
  if (this->has_http_request()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *http_request_);
  }

  // .google.api.MonitoredResource resource = 8;
  if (this->has_resource()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *resource_);
  }

  // .google.protobuf.Timestamp timestamp = 9;
  if (this->has_timestamp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *timestamp_);
  }

  // .google.logging.v2.LogEntryOperation operation = 15;
  if (this->has_operation()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *operation_);
  }

  // .google.logging.v2.LogEntrySourceLocation source_location = 23;
  if (this->has_source_location()) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *source_location_);
  }

  // .google.protobuf.Timestamp receive_timestamp = 24;
  if (this->has_receive_timestamp()) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *receive_timestamp_);
  }

  // .google.api.MonitoredResourceMetadata metadata = 25;
  if (this->has_metadata()) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *metadata_);
  }

  // .google.logging.type.LogSeverity severity = 10;
  if (this->severity() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->severity());
  }

  // bool trace_sampled = 30;
  if (this->trace_sampled() != 0) {
    total_size += 2 + 1;
  }

  switch (payload_case()) {
    // .google.protobuf.Any proto_payload = 2;
    case kProtoPayload: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *payload_.proto_payload_);
      break;
    }
    // string text_payload = 3;
    case kTextPayload: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->text_payload());
      break;
    }
    // .google.protobuf.Struct json_payload = 6;
    case kJsonPayload: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *payload_.json_payload_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LogEntry::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const LogEntry*>(&from));
}

void LogEntry::MergeFrom(const LogEntry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.logging.v2.LogEntry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  labels_.MergeFrom(from.labels_);
  if (from.insert_id().size() > 0) {
    set_insert_id(from.insert_id());
  }
  if (from.log_name().size() > 0) {
    set_log_name(from.log_name());
  }
  if (from.trace().size() > 0) {
    set_trace(from.trace());
  }
  if (from.span_id().size() > 0) {
    set_span_id(from.span_id());
  }
  if (from.has_http_request()) {
    mutable_http_request()->::google::logging::type::HttpRequest::MergeFrom(from.http_request());
  }
  if (from.has_resource()) {
    mutable_resource()->::google::api::MonitoredResource::MergeFrom(from.resource());
  }
  if (from.has_timestamp()) {
    mutable_timestamp()->::google::protobuf::Timestamp::MergeFrom(from.timestamp());
  }
  if (from.has_operation()) {
    mutable_operation()->::google::logging::v2::LogEntryOperation::MergeFrom(from.operation());
  }
  if (from.has_source_location()) {
    mutable_source_location()->::google::logging::v2::LogEntrySourceLocation::MergeFrom(from.source_location());
  }
  if (from.has_receive_timestamp()) {
    mutable_receive_timestamp()->::google::protobuf::Timestamp::MergeFrom(from.receive_timestamp());
  }
  if (from.has_metadata()) {
    mutable_metadata()->::google::api::MonitoredResourceMetadata::MergeFrom(from.metadata());
  }
  if (from.severity() != 0) {
    set_severity(from.severity());
  }
  if (from.trace_sampled() != 0) {
    set_trace_sampled(from.trace_sampled());
  }
  switch (from.payload_case()) {
    case kProtoPayload: {
      mutable_proto_payload()->::google::protobuf::Any::MergeFrom(from.proto_payload());
      break;
    }
    case kTextPayload: {
      set_text_payload(from.text_payload());
      break;
    }
    case kJsonPayload: {
      mutable_json_payload()->::google::protobuf::Struct::MergeFrom(from.json_payload());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
}

void LogEntry::CopyFrom(const LogEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.logging.v2.LogEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogEntry::IsInitialized() const {
  return true;
}

void LogEntry::Swap(LogEntry* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    LogEntry* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void LogEntry::UnsafeArenaSwap(LogEntry* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void LogEntry::InternalSwap(LogEntry* other) {
  using std::swap;
  labels_.Swap(&other->labels_);
  insert_id_.Swap(&other->insert_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  log_name_.Swap(&other->log_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  trace_.Swap(&other->trace_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  span_id_.Swap(&other->span_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(http_request_, other->http_request_);
  swap(resource_, other->resource_);
  swap(timestamp_, other->timestamp_);
  swap(operation_, other->operation_);
  swap(source_location_, other->source_location_);
  swap(receive_timestamp_, other->receive_timestamp_);
  swap(metadata_, other->metadata_);
  swap(severity_, other->severity_);
  swap(trace_sampled_, other->trace_sampled_);
  swap(payload_, other->payload_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string LogEntry::GetTypeName() const {
  return "google.logging.v2.LogEntry";
}


// ===================================================================

void LogEntryOperation::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LogEntryOperation::kIdFieldNumber;
const int LogEntryOperation::kProducerFieldNumber;
const int LogEntryOperation::kFirstFieldNumber;
const int LogEntryOperation::kLastFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LogEntryOperation::LogEntryOperation()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntryOperation.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.logging.v2.LogEntryOperation)
}
LogEntryOperation::LogEntryOperation(::google::protobuf::Arena* arena)
  : ::google::protobuf::MessageLite(),
  _internal_metadata_(arena) {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntryOperation.base);
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.logging.v2.LogEntryOperation)
}
LogEntryOperation::LogEntryOperation(const LogEntryOperation& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.id().size() > 0) {
    id_.SetLite(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id(),
      GetArenaNoVirtual());
  }
  producer_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.producer().size() > 0) {
    producer_.SetLite(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.producer(),
      GetArenaNoVirtual());
  }
  ::memcpy(&first_, &from.first_,
    static_cast<size_t>(reinterpret_cast<char*>(&last_) -
    reinterpret_cast<char*>(&first_)) + sizeof(last_));
  // @@protoc_insertion_point(copy_constructor:google.logging.v2.LogEntryOperation)
}

void LogEntryOperation::SharedCtor() {
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  producer_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&first_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&last_) -
      reinterpret_cast<char*>(&first_)) + sizeof(last_));
}

LogEntryOperation::~LogEntryOperation() {
  // @@protoc_insertion_point(destructor:google.logging.v2.LogEntryOperation)
  SharedDtor();
}

void LogEntryOperation::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
  id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  producer_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LogEntryOperation::ArenaDtor(void* object) {
  LogEntryOperation* _this = reinterpret_cast< LogEntryOperation* >(object);
  (void)_this;
}
void LogEntryOperation::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void LogEntryOperation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LogEntryOperation& LogEntryOperation::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntryOperation.base);
  return *internal_default_instance();
}


void LogEntryOperation::Clear() {
// @@protoc_insertion_point(message_clear_start:google.logging.v2.LogEntryOperation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  producer_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  ::memset(&first_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&last_) -
      reinterpret_cast<char*>(&first_)) + sizeof(last_));
  _internal_metadata_.Clear();
}

bool LogEntryOperation::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:google.logging.v2.LogEntryOperation)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->id().data(), static_cast<int>(this->id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.logging.v2.LogEntryOperation.id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string producer = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_producer()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->producer().data(), static_cast<int>(this->producer().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.logging.v2.LogEntryOperation.producer"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool first = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &first_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool last = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &last_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.logging.v2.LogEntryOperation)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.logging.v2.LogEntryOperation)
  return false;
#undef DO_
}

void LogEntryOperation::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.logging.v2.LogEntryOperation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (this->id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id().data(), static_cast<int>(this->id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.logging.v2.LogEntryOperation.id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->id(), output);
  }

  // string producer = 2;
  if (this->producer().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->producer().data(), static_cast<int>(this->producer().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.logging.v2.LogEntryOperation.producer");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->producer(), output);
  }

  // bool first = 3;
  if (this->first() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->first(), output);
  }

  // bool last = 4;
  if (this->last() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->last(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:google.logging.v2.LogEntryOperation)
}

size_t LogEntryOperation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.logging.v2.LogEntryOperation)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string id = 1;
  if (this->id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->id());
  }

  // string producer = 2;
  if (this->producer().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->producer());
  }

  // bool first = 3;
  if (this->first() != 0) {
    total_size += 1 + 1;
  }

  // bool last = 4;
  if (this->last() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LogEntryOperation::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const LogEntryOperation*>(&from));
}

void LogEntryOperation::MergeFrom(const LogEntryOperation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.logging.v2.LogEntryOperation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id().size() > 0) {
    set_id(from.id());
  }
  if (from.producer().size() > 0) {
    set_producer(from.producer());
  }
  if (from.first() != 0) {
    set_first(from.first());
  }
  if (from.last() != 0) {
    set_last(from.last());
  }
}

void LogEntryOperation::CopyFrom(const LogEntryOperation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.logging.v2.LogEntryOperation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogEntryOperation::IsInitialized() const {
  return true;
}

void LogEntryOperation::Swap(LogEntryOperation* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    LogEntryOperation* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void LogEntryOperation::UnsafeArenaSwap(LogEntryOperation* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void LogEntryOperation::InternalSwap(LogEntryOperation* other) {
  using std::swap;
  id_.Swap(&other->id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  producer_.Swap(&other->producer_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(first_, other->first_);
  swap(last_, other->last_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string LogEntryOperation::GetTypeName() const {
  return "google.logging.v2.LogEntryOperation";
}


// ===================================================================

void LogEntrySourceLocation::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LogEntrySourceLocation::kFileFieldNumber;
const int LogEntrySourceLocation::kLineFieldNumber;
const int LogEntrySourceLocation::kFunctionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LogEntrySourceLocation::LogEntrySourceLocation()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntrySourceLocation.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.logging.v2.LogEntrySourceLocation)
}
LogEntrySourceLocation::LogEntrySourceLocation(::google::protobuf::Arena* arena)
  : ::google::protobuf::MessageLite(),
  _internal_metadata_(arena) {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntrySourceLocation.base);
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.logging.v2.LogEntrySourceLocation)
}
LogEntrySourceLocation::LogEntrySourceLocation(const LogEntrySourceLocation& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  file_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.file().size() > 0) {
    file_.SetLite(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.file(),
      GetArenaNoVirtual());
  }
  function_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.function().size() > 0) {
    function_.SetLite(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.function(),
      GetArenaNoVirtual());
  }
  line_ = from.line_;
  // @@protoc_insertion_point(copy_constructor:google.logging.v2.LogEntrySourceLocation)
}

void LogEntrySourceLocation::SharedCtor() {
  file_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  function_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  line_ = GOOGLE_LONGLONG(0);
}

LogEntrySourceLocation::~LogEntrySourceLocation() {
  // @@protoc_insertion_point(destructor:google.logging.v2.LogEntrySourceLocation)
  SharedDtor();
}

void LogEntrySourceLocation::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
  file_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  function_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LogEntrySourceLocation::ArenaDtor(void* object) {
  LogEntrySourceLocation* _this = reinterpret_cast< LogEntrySourceLocation* >(object);
  (void)_this;
}
void LogEntrySourceLocation::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void LogEntrySourceLocation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LogEntrySourceLocation& LogEntrySourceLocation::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2flogging_2fv2_2flog_5fentry_2eproto::scc_info_LogEntrySourceLocation.base);
  return *internal_default_instance();
}


void LogEntrySourceLocation::Clear() {
// @@protoc_insertion_point(message_clear_start:google.logging.v2.LogEntrySourceLocation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  file_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  function_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  line_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool LogEntrySourceLocation::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:google.logging.v2.LogEntrySourceLocation)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string file = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_file()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->file().data(), static_cast<int>(this->file().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.logging.v2.LogEntrySourceLocation.file"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 line = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &line_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string function = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_function()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->function().data(), static_cast<int>(this->function().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.logging.v2.LogEntrySourceLocation.function"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.logging.v2.LogEntrySourceLocation)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.logging.v2.LogEntrySourceLocation)
  return false;
#undef DO_
}

void LogEntrySourceLocation::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.logging.v2.LogEntrySourceLocation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string file = 1;
  if (this->file().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->file().data(), static_cast<int>(this->file().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.logging.v2.LogEntrySourceLocation.file");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->file(), output);
  }

  // int64 line = 2;
  if (this->line() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->line(), output);
  }

  // string function = 3;
  if (this->function().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->function().data(), static_cast<int>(this->function().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.logging.v2.LogEntrySourceLocation.function");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->function(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:google.logging.v2.LogEntrySourceLocation)
}

size_t LogEntrySourceLocation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.logging.v2.LogEntrySourceLocation)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string file = 1;
  if (this->file().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->file());
  }

  // string function = 3;
  if (this->function().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->function());
  }

  // int64 line = 2;
  if (this->line() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->line());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LogEntrySourceLocation::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const LogEntrySourceLocation*>(&from));
}

void LogEntrySourceLocation::MergeFrom(const LogEntrySourceLocation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.logging.v2.LogEntrySourceLocation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.file().size() > 0) {
    set_file(from.file());
  }
  if (from.function().size() > 0) {
    set_function(from.function());
  }
  if (from.line() != 0) {
    set_line(from.line());
  }
}

void LogEntrySourceLocation::CopyFrom(const LogEntrySourceLocation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.logging.v2.LogEntrySourceLocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogEntrySourceLocation::IsInitialized() const {
  return true;
}

void LogEntrySourceLocation::Swap(LogEntrySourceLocation* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    LogEntrySourceLocation* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void LogEntrySourceLocation::UnsafeArenaSwap(LogEntrySourceLocation* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void LogEntrySourceLocation::InternalSwap(LogEntrySourceLocation* other) {
  using std::swap;
  file_.Swap(&other->file_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  function_.Swap(&other->function_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(line_, other->line_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string LogEntrySourceLocation::GetTypeName() const {
  return "google.logging.v2.LogEntrySourceLocation";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v2
}  // namespace logging
}  // namespace google
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::logging::v2::LogEntry_LabelsEntry_DoNotUse* Arena::CreateMaybeMessage< ::google::logging::v2::LogEntry_LabelsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::logging::v2::LogEntry_LabelsEntry_DoNotUse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::logging::v2::LogEntry* Arena::CreateMaybeMessage< ::google::logging::v2::LogEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::logging::v2::LogEntry >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::logging::v2::LogEntryOperation* Arena::CreateMaybeMessage< ::google::logging::v2::LogEntryOperation >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::logging::v2::LogEntryOperation >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::logging::v2::LogEntrySourceLocation* Arena::CreateMaybeMessage< ::google::logging::v2::LogEntrySourceLocation >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::logging::v2::LogEntrySourceLocation >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
