load(
    "@envoy//bazel:envoy_build_system.bzl",
    "envoy_proto_library",
)

licenses(["notice"])  # Apache 2

envoy_proto_library(
    name = "stackdriver_module_proto",
    srcs = ["stackdriver_module.proto"],
)