load(
    "@envoy//bazel:envoy_build_system.bzl",
    "envoy_proto_library",
)

envoy_proto_library(
    name = "http_request_proto",
    srcs = ["http_request.proto"],
)

envoy_proto_library(
    name = "log_severity_proto",
    srcs = ["log_severity.proto"],
)